require("../../common/base.scss")
require("../select/index.scss")
require("../../button/index.scss")
require("../components/test.css")
require("../components/components2/test2.css")
require("../components3/test3.css")