version: "3"
services:
    web:
        image: sparkle:v1
        container_name: sparkle_web_nginx
        ports:
        - "2333:2333"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        # - /web:/usr/share/nginx/html
        command: /bin/bash -c "nginx -g 'daemon off;'"
