require("../../common/base.css")
require("../index.css")
require("../../button/index.css")
require("../components/test.css")
require("../components/components2/test2.css")
require("../components3/test3.css")